/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-30 12:56:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".header {\r\n");
      out.write("	background-color:brown;\r\n");
      out.write("	padding: 20px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header a {\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header a.logo {\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo img {\r\n");
      out.write("	width: 50px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write(".header-left {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	margin-left: 0px;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-center {\r\n");
      out.write("	outline-color: white;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding-top: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-right {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buttons {\r\n");
      out.write("	border-radius: 7px;\r\n");
      out.write("	font-weight: 500px;\r\n");
      out.write("	background-color: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"header\">\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"header-left\">\r\n");
      out.write("				<li><a href=\"deafult.asp\" class=\"logo\"><img\r\n");
      out.write("						src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyjErq4K9T0yZqmHvlYfTncPzvLM-iKsNIcA&usqp=CAU\"\r\n");
      out.write("						alt=\"logo\"></a></li>\r\n");
      out.write("				<li><button class=\"buttons\">\r\n");
      out.write("						<a href=\"/SpringEcommerce/plp/Men\"> MEN</a>\r\n");
      out.write("					</button></li>\r\n");
      out.write("				<li><button class=\"buttons\">\r\n");
      out.write("						<a href=\"/SpringEcommerce/plp/Women\">WOMEN</a>\r\n");
      out.write("					</button></li>\r\n");
      out.write("				<li><button class=\"buttons\">\r\n");
      out.write("						<a href=\"/SpringEcommerce/plp/Kids\">KIDS</a>\r\n");
      out.write("					</button></li>\r\n");
      out.write("				<li><button class=\"buttons\">\r\n");
      out.write("						<a href=\"#show_message\">EXPLORE</a>\r\n");
      out.write("					</button></li>\r\n");
      out.write("				<li><button class=\"buttons\">\r\n");
      out.write("						<a href=\"#show_message\">SALE</a>\r\n");
      out.write("					</button></li>\r\n");
      out.write("				<li><input type=\"search\" value=\"\"\r\n");
      out.write("					placeholder=\"Search for Products and Brands More\"\r\n");
      out.write("					style=\"width: 250px; height: 30px; border-radius: 10px; border: 1px solid black;\"></li>\r\n");
      out.write("				<li><button class=\"buttons\">\r\n");
      out.write("						<a href=\"/SpringEcommerce/cart\"><svg\r\n");
      out.write("								xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\"\r\n");
      out.write("								fill=\"currentColor\" class=\"bi bi-cart4\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                            <path\r\n");
      out.write("									d=\"M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z\" />\r\n");
      out.write("                          </svg></a>\r\n");
      out.write("					</button></li>\r\n");
      out.write("				<li><button class=\"buttons\">\r\n");
      out.write("						<a href=\"/SpringEcommerce/order\">ORDER</a>\r\n");
      out.write("					</button></li>\r\n");
      out.write("				<li><button class=\"buttons\">\r\n");
      out.write("						<a href=\"/SpringEcommerce/logout\">LOGOUT</a>\r\n");
      out.write("					</button></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
