/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-30 12:57:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width; initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<title>REEBOK OLD SCHOOL</title>\r\n");
      out.write("<style>\r\n");
      out.write(".body {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buttons {\r\n");
      out.write("	border-radius: 7px;\r\n");
      out.write("	font-weight: 500px;\r\n");
      out.write("	background-color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#fname {\r\n");
      out.write("	height: 25px;\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	background-color: rgb(255, 255, 255);\r\n");
      out.write("	margin-right: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shirt-one a {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	line-height: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#T-shirt img {\r\n");
      out.write("	width: 240px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	box-sizing: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shirts-one {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div>\r\n");
      out.write("		<img\r\n");
      out.write("			src=\"https://content.shop4reebok.com/static/hero/RBK_Outlet_1920x800_160322_Homepage.jpg\">\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"Shirts\"\r\n");
      out.write("		style=\"margin-top: 30px; background-color: lightslategray;\">\r\n");
      out.write("		<div class=\"shirts-one\">\r\n");
      out.write("			<a id=\"T-shirt\"> <img\r\n");
      out.write("				src=\"https://content.shop4reebok.com/static/spotlight/RBK_Website_Banners_Shoes_130821.jpg\"\r\n");
      out.write("				alt=\"SPT1_SHOES_130821\" style=\"width: 100%; height: auto;\"></a> <a\r\n");
      out.write("				id=\"T-shirt\"> <img\r\n");
      out.write("				src=\"https://content.shop4reebok.com/static/spotlight/Apparel_SL_WEB_060122.jpg\"\r\n");
      out.write("				alt=\"APPAREL\" style=\"width: 100%; height: auto;\"></a> <a\r\n");
      out.write("				id=\"T-shirt\"> <img\r\n");
      out.write("				src=\"https://content.shop4reebok.com/static/spotlight/Accessories_spotlight_960x480_15th_Sept.jpg\"\r\n");
      out.write("				alt=\"ACCESSORIES \" style=\"width: 100%; height: auto;\"></a> <a\r\n");
      out.write("				id=\"T-shirt\"> <img\r\n");
      out.write("				src=\"https://content.shop4reebok.com/static/spotlight/NewArrivals_SL_WEB_280322.jpg\"\r\n");
      out.write("				alt=\"SPT3_NewArrivals_SL_280322\" style=\"width: 100%; height: auto;\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br> <br> <br>\r\n");
      out.write("		<div class=\"Shirts\"\r\n");
      out.write("			style=\"margin-top: 50px; background-color: lightslategray;\">\r\n");
      out.write("			<div class=\"shirts-one\">\r\n");
      out.write("				<a id=\"T-shirt\"> <img\r\n");
      out.write("					src=\"https://brand.assets.reebok.com/image/upload/f_auto,q_auto,fl_lossy/reebok_enUS/Images/22SS_Adaptive-Collection-Fit-to-Fit_FD_Teaser-Carousel-Card_tcm274-888503.jpg\"\r\n");
      out.write("					alt=\"SPT1_SHOES_130821\" style=\"width: 100%; height: auto;\"></a> <a\r\n");
      out.write("					id=\"T-shirt\"> <img\r\n");
      out.write("					src=\"https://brand.assets.reebok.com/image/upload/f_auto,q_auto,fl_lossy/reebok_enUS/Images/22SS_ZigDynamica-FamilyShots_FD_Teaser-Carousel-Card-Background_tcm274-887621.jpg\"\r\n");
      out.write("					alt=\"SPT1_SHOES_130821\" style=\"width: 100%; height: auto;\"></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img\r\n");
      out.write("				src=\"https://content.shop4reebok.com/static/explore/10_pct_prepaid_1Oct.png\"\r\n");
      out.write("				alt=\"\" style=\"margin: 0 auto;\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"popular\">\r\n");
      out.write("			<div\r\n");
      out.write("				style=\"text-align: center; font-size: 40px; line-height: 40px; text-transform: uppercase; letter-spacing: 1px; font-family: NeuePlakWideRegular; color: #000000; margin-bottom: 20px;\">TRENDING\r\n");
      out.write("				NOW</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<div class=\"Shirts\" style=\"margin-top: 50px;\">\r\n");
      out.write("				<div class=\"shirts-one\">\r\n");
      out.write("					<a id=\"T-shirt\"> <img\r\n");
      out.write("						src=\"https://content.shop4reebok.com/static/explore/RBK_EN_Training_Essentials_040522_960x480.jpg\"\r\n");
      out.write("						alt=\"\" class=\"cta-image\" style=\"width: 100%; height: auto;\"></a>\r\n");
      out.write("					<a id=\"T-shirt\"> <img\r\n");
      out.write("						src=\"https://content.shop4reebok.com/static/explore/RBK_EN_Money_Heist_050522_960x480.jpg\"\r\n");
      out.write("						alt=\"\" class=\"cta-image\" style=\"width: 100%; height: auto;\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<div class=\"Shirts\" style=\"margin-top: 50px;\">\r\n");
      out.write("				<div class=\"shirts-one\">\r\n");
      out.write("					<a id=\"T-shirt\"> <img\r\n");
      out.write("						src=\"https://content.shop4reebok.com/static/explore/RBK_EN_Athleisure_040522_960x480.jpg\"\r\n");
      out.write("						alt=\"\" class=\"cta-image\" style=\"width: 100%; height: auto;\"></a>\r\n");
      out.write("					<a id=\"T-shirt\"><img\r\n");
      out.write("						src=\"https://content.shop4reebok.com/static/explore/RBK_EN_Running_Gear_040522_960x480.jpg\"\r\n");
      out.write("						alt=\"\" class=\"cta-image\" style=\"width: 100%; height: auto;\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
